### PR TITLE
Switched to AsyncKeyedLock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This change will improve performance as well as reduce memory allocations.

### CODE REVIEW

**Comment by trudyhood** [comment]
Hi, Thank you for your contribution to our project with the async lock library. We appreciate your effort in improving the performance and memory efficiency of our code. We have checked it in various methods and we found it faster and more efficient.

After thorough consideration, we have decided to not to merge the commit. While the added functionality is certainly valuable, we have determined that the added complexity and dependency is not in line with our current goals for the project. Especially that we don't use named async lock in high loaded part, perhaps less than 1000 calls per day.

Our priority is to maintain a simple and straightforward codebase that is easy to understand and maintain. Given that the async lock is not used in high-intensive parts of the code, we believe that the added complexity and dependency outweigh the benefits in this particular case.

Thank you again for your contribution, and we hope you will understand our decision. If you have any questions or concerns, please don't hesitate to reach out.

**Comment by MarkCiliaVincenti** [comment]
@trudyhood I took a look at the current code again and I noticed a race condition.

For example, thread A fires for key "ABC" and is releasing the semaphore (inside the Dispose method).
Thread B fires for key "ABC" as well, obtains the lock for the dictionary and the GetOrAdd gets as thread A had created the dictionary item with key "ABC", exits the lock and is suspended by the OS.
Thread A goes inside the lock for the dictionary, finds _semaphoreSlim.CurrentCount to be 0 and removes the entry from the dictionary.
Thread B is resumed by the OS, awaits on a semaphore that is no longer in the dictionary, and returns the releaser.
Thread C now fires for key "ABC", does not find "ABC" in the dictionary (as thread A had removed it), and concurrently executes for key "ABC" whilst thread B is doing the same thing.

The library in the PR (of which I am the author) takes care of such rare race conditions and is tried and tested in several production environments.

**Comment by trudyhood** [comment]
@MarkCiliaVincenti  Such sharp eyes you have! 👌 
I am really appreciated and thank you for reporting this to us.

Yes, I shouldn't count on SemaphoreSlim.CurrentCount, as I couldn't use it in thread lock. I fixed the code and used reference count instead.
https://github.com/vpnhood/VpnHood/blob/development/VpnHood.Common/Utils/AsyncLock.cs

Regarding AsyncKeyedLock, I believe in it, and I am sure it is far better than ours; I hope Microsoft adds it as part of the .net standard library. VpnHood widely uses pure semaphore (unnamed). It merely uses named semaphores, so we still prefer simpler code for this case. We definitely use your code if we need to use a named async lock in any performance-sensitive section.

**Comment by MarkCiliaVincenti** [comment]
Thank you for your kind words.

Using the reference count, inside the lock, indeed solves the race condition.

**Pull request closed without merging**
